### ISSUE TITLE
scanner.Bytes() not safe to use after scanner.Scan() is called

### ISSUE THREAD

**Issue by helinwang** [eclesh/recordio#2]
Need a copy, otherwise the data would be corrupted:

```go
ch := make(chan []byte, 10)
for scanner.Scan() {
                b := scanner.Bytes()
                cpy := make([]byte, len(b))
                copy(cpy, b)
                ch <- cpy
}
```

**Comment by eclesh** [comment]
Thanks for the report! I've added documentation indicating that this is necessary. The design is meant to copy `bufio.Scanner`, which requires the same `copy`. Hopefully the need for the `copy` isn't too surprising, given the example set by the standard library. Thanks again for taking a look at recordio.
